name: Java Continuous Integration

on:
  push:
    branches:
      - master
    # Ignore changes in documentation and reports
    paths-ignore: 
      - 'showcase-quarkus-eventsourcing/native-image-agent-results/**'
      - '**/*.md'
      - '**/*.txt'
      - '.gitignore'
      - '.gitattributes'
      - 'renovate.json'
      - 'changelogTemplate.mustache'
  pull_request:
    branches:
      - master
    # Ignore changes in documentation and reports
    paths-ignore: 
      - 'showcase-quarkus-eventsourcing/native-image-agent-results/**'
      - '**/*.md'
      - '**/*.txt'
      - '.gitignore'
      - '.gitattributes'
      - 'renovate.json'
      - 'changelogTemplate.mustache'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [17]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Build with Maven
      working-directory: showcase-quarkus-eventsourcing
      run: mvn -B package --file pom.xml
