name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11
        cache: 'maven'
    - name: Build with Maven
      working-directory: showcase-quarkus-eventsourcing
      run: mvn -B package --file pom.xml
