name: Java Continuous Integration (PostgreSQL)

on:
  push:
    branches:
      - master
    # Ignore changes in documentation and reports
    paths-ignore: 
      - 'showcase-quarkus-eventsourcing/native-image-agent-results/**'
      - '**/*.md'
      - '**/*.txt'
      - '.gitignore'
      - '.gitattributes'
      - 'renovate.json'
      - 'changelogTemplate.mustache'
  pull_request:
    branches:
      - master
    # Ignore changes in documentation and reports
    paths-ignore: 
      - 'showcase-quarkus-eventsourcing/native-image-agent-results/**'
      - '**/*.md'
      - '**/*.txt'
      - '.gitignore'
      - '.gitattributes'
      - 'renovate.json'
      - 'changelogTemplate.mustache'

jobs:
  # Label of the container job
  postgresql-build:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `postgresql-build` executes in
    container: maven:3.8.7-openjdk-18

    # Service containers to run with `postgresql-build`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build with Maven, Test with PostgreSql
        working-directory: showcase-quarkus-eventsourcing
        run: mvn verify -Dquarkus.profile=postgres --file pom.xml --batch-mode
        env:
          # The hostname used to communicate with the PostgreSQL service container
          POSTGRES_HOST: postgres
          # The default PostgreSQL port
          POSTGRES_PORT: 5432